# Generated by Django 5.0.1 on 2024-02-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='area',
        ),
    ]
